### ISSUE TITLE
Double "*"

### ISSUE THREAD

**Issue by jomarcenter-mjm** [jomarcenter-mjm/RPGMakerMVPluginSnippet#1]
A bug report was created as the problem is if you already have called @type while * is already added it will just add another * regardless making it a double *.

**Comment by jomarcenter-mjm** [comment]
a 1.3.0 update will be issue with the bug fix.
For now a testing phase is added for the community to test this new version on 1.3.0 for community input.

**Comment by trapless** [comment]
1.3.0-test fixed the bug for me.

**Comment by jomarcenter-mjm** [comment]
Verified that this bug have been fixed and will be closed.
