### ISSUE TITLE
Build instructions on readme

### ISSUE THREAD

**Issue by trapless** [jomarcenter-mjm/RPGMakerMVPluginSnippet#5]
I think it's a good idea for all git repos to explain build instructions on their Readme.md

It welcomes people to contribute to the project and helps aspiring developers learn about git. I see a lot of build instructions for projects on readme pages. I think it may be best practice.

![image](https://user-images.githubusercontent.com/980081/71005194-3775f900-20b1-11ea-83ef-a9e84eccffee.png)

**Comment by jomarcenter-mjm** [comment]
Will see what I can do.

**Comment by jomarcenter-mjm** [comment]
Build instruction have been added. if it insufficient anyone can reopen this ticket.
