### ISSUE TITLE
[Bug] prototype snippet causes interference

### ISSUE THREAD

**Issue by trapless** [jomarcenter-mjm/RPGMakerMVPluginSnippet#6]
Problem: prototype snippet writes a function into the document on carriage return or tab after period.

Expected: a clean new line for text.

example:
![image](https://user-images.githubusercontent.com/980081/71063172-3210c100-213a-11ea-9f14-efcecc652914.png)
![image](https://user-images.githubusercontent.com/980081/71063197-3fc64680-213a-11ea-991d-1298c2f9175e.png)

possible solution: offer snippet after `  .p  ` instead of `  .  `

**Comment by jomarcenter-mjm** [comment]
will see what I can do, I may just get rid of it tho

**Comment by jomarcenter-mjm** [comment]
please confirm the fix.

**Comment by trapless** [comment]
![image](https://user-images.githubusercontent.com/980081/71220178-a744d900-2295-11ea-8b34-1d40683b680e.png)
Not yet.
